version: "3"

services:
  # https://nodejs.org
  node:
    container_name: nws-node
    restart: no
    build:
      context: .
      dockerfile: node/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src

  # https://nginx.org/
  nginx:
    container_name: nws-nginx
    depends_on:
      - node
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    tty: true
    ports:
      - ${PORT_WEBSITE}:3000
    volumes:
      - ../:/var/www/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
